[workspace]
channels = ["conda-forge"]
name = "adamdoescode.github.io"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
ruby = "3.3.*"
python = ">=3.12"
zlib = ">=1.3.1"

[tasks]
bundle-install = "bundle install"
jekyll-serve = "bundle exec jekyll serve"
jekyll-build = "bundle exec jekyll build"

